# Generated by Django 4.2.11 on 2024-04-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=600)),
                ('prompt', models.CharField(max_length=100)),
                ('createDate', models.DateField()),
            ],
        ),
    ]
