# Generated by Django 4.2.11 on 2024-04-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(default='stories/book.png', upload_to='stories/'),
        ),
        migrations.AddField(
            model_name='story',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='createDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
