# Generated by Django 4.2.11 on 2024-04-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_story_image_story_ispublic_alter_story_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.TextField(default='ar'),
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='wordSize',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
