# Generated by Django 4.2.11 on 2024-04-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_story_author_alter_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='createDate',
            field=models.DateField(),
        ),
    ]
