# Generated by Django 4.2.11 on 2024-04-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_story_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='createDate',
            field=models.DateField(auto_now=True),
        ),
    ]
