# Generated by Django 4.2.11 on 2024-04-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_story_createdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='id',
        ),
        migrations.AddField(
            model_name='story',
            name='storyId',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
