# Generated by Django 4.2.11 on 2024-04-20 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0007_remove_story_id_story_storyid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('bio', models.TextField(null=True)),
                ('UserId', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='profiles/default_profile.png', upload_to='profiles/<django.db.models.fields.BigAutoField>')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
