# Generated by Django 4.2.11 on 2024-04-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_profile_country_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='UserId',
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profiles/default_profile.png', upload_to='profiles/<django.db.models.query_utils.DeferredAttribute object at 0x000001AF8FAF2190>'),
        ),
    ]
