# Generated by Django 4.2.11 on 2024-05-01 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0016_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostLanguage', models.CharField(choices=[('en-US', 'English'), ('es-ES', 'Spanish'), ('de-DE', 'German'), ('fr-FR', 'French'), ('tr-TR', 'Turkish'), ('ar-XA', 'Arabic'), ('it-IT', 'Italian'), ('ru-RU', 'Russian')], default='English', max_length=50)),
                ('ReadingLanguage', models.CharField(choices=[('en-US', 'English'), ('es-ES', 'Spanish'), ('de-DE', 'German'), ('fr-FR', 'French'), ('tr-TR', 'Turkish'), ('ar-XA', 'Arabic'), ('it-IT', 'Italian'), ('ru-RU', 'Russian')], default='English', max_length=50)),
                ('TranscribeLanguage', models.CharField(choices=[('en-US', 'English'), ('es-ES', 'Spanish'), ('de-DE', 'German'), ('fr-FR', 'French'), ('tr-TR', 'Turkish'), ('ar-XA', 'Arabic'), ('it-IT', 'Italian'), ('ru-RU', 'Russian')], default='English', max_length=50)),
                ('GenerativeLanguage', models.CharField(choices=[('en-US', 'English'), ('es-ES', 'Spanish'), ('de-DE', 'German'), ('fr-FR', 'French'), ('tr-TR', 'Turkish'), ('ar-XA', 'Arabic'), ('it-IT', 'Italian'), ('ru-RU', 'Russian')], default='English', max_length=50)),
                ('Reader_gender', models.CharField(choices=[('A', 'Male'), ('B', 'Female')], default='English', max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
