# Generated by Django 4.2.11 on 2024-05-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_languagesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagesetting',
            name='Reader_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='English', max_length=50),
        ),
    ]
