# Generated by Django 4.2.11 on 2024-05-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_alter_interactive_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactive',
            name='history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
