# Generated by Django 4.2.11 on 2024-05-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_alter_interactive_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interactive_Story',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='interactive',
            name='contents',
            field=models.ManyToManyField(to='pages.interactive_story'),
        ),
    ]
