# Generated by Django 4.2.11 on 2024-05-05 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_interactive_story_interactive_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactive',
            name='contents',
        ),
    ]
