# Generated by Django 4.2.11 on 2024-05-05 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_remove_interactive_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactive_story',
            name='partOf',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='pages.interactive'),
            preserve_default=False,
        ),
    ]
