# Generated by Django 4.2.11 on 2024-05-05 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_interactive_story_partof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactive',
            name='history',
        ),
        migrations.CreateModel(
            name='Interactive_History',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('element', models.TextField(blank=True, null=True)),
                ('historyOf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.interactive')),
            ],
        ),
    ]
