# Generated by Django 4.2.11 on 2024-05-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_remove_interactive_history_interactive_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interactive_History',
        ),
    ]
