# Generated by Django 4.2.11 on 2024-05-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_delete_interactive_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveGame',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('music', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='interactive',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
