# Generated by Django 4.2.11 on 2024-05-05 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_interactivegame_interactive_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactive',
            name='gameOf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.interactivegame'),
        ),
    ]
