# Generated by Django 4.2.11 on 2024-05-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_interactivecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactive_story',
            name='text',
        ),
        migrations.AddField(
            model_name='interactive_story',
            name='parts',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='interactive_story',
            name='roles',
            field=models.TextField(null=True),
        ),
    ]
