# Generated by Django 4.2.11 on 2024-05-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_uploadedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
        migrations.AddField(
            model_name='profile',
            name='isEmailVerified',
            field=models.BooleanField(default=False),
        ),
    ]
