# Generated by Django 4.2.11 on 2024-05-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_rename_extractedpdf_pdf_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='content',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
