# Generated by Django 4.2.11 on 2024-05-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_pdf_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='content',
            field=models.FileField(default=1, upload_to='pdfs/'),
            preserve_default=False,
        ),
    ]
