# Generated by Django 4.2.11 on 2024-05-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_alter_pdf_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
