# Generated by Django 4.2.11 on 2024-05-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_alter_pdf_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='image',
        ),
        migrations.AddField(
            model_name='pdf',
            name='image',
            field=models.ImageField(default=1, upload_to='pdfs/images/'),
            preserve_default=False,
        ),
    ]
