# Generated by Django 4.2.11 on 2024-05-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_remove_page_image_pdf_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagesetting',
            name='GenerativeLanguage',
            field=models.CharField(choices=[('en-US', 'English'), ('es-ES', 'Spanish'), ('de-DE', 'German'), ('fr-FR', 'French'), ('tr-TR', 'Turkish'), ('ar-XA', 'Arabic'), ('it-IT', 'Italian'), ('ru-RU', 'Russian')], default='en-US', max_length=50),
        ),
        migrations.AlterField(
            model_name='languagesetting',
            name='PostLanguage',
            field=models.CharField(choices=[('en-US', 'English'), ('es-ES', 'Spanish'), ('de-DE', 'German'), ('fr-FR', 'French'), ('tr-TR', 'Turkish'), ('ar-XA', 'Arabic'), ('it-IT', 'Italian'), ('ru-RU', 'Russian')], default='en-US', max_length=50),
        ),
        migrations.AlterField(
            model_name='languagesetting',
            name='Reader_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50),
        ),
        migrations.AlterField(
            model_name='languagesetting',
            name='ReadingLanguage',
            field=models.CharField(choices=[('en-US', 'English'), ('es-ES', 'Spanish'), ('de-DE', 'German'), ('fr-FR', 'French'), ('tr-TR', 'Turkish'), ('ar-XA', 'Arabic'), ('it-IT', 'Italian'), ('ru-RU', 'Russian')], default='en-US', max_length=50),
        ),
        migrations.AlterField(
            model_name='languagesetting',
            name='TranscribeLanguage',
            field=models.CharField(choices=[('en-US', 'English'), ('es-ES', 'Spanish'), ('de-DE', 'German'), ('fr-FR', 'French'), ('tr-TR', 'Turkish'), ('ar-XA', 'Arabic'), ('it-IT', 'Italian'), ('ru-RU', 'Russian')], default='en-US', max_length=50),
        ),
    ]
