# Generated by Django 4.2.11 on 2024-05-31 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0042_alter_languagesetting_generativelanguage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.AddField(
            model_name='interactivegame',
            name='numberOfPlayer',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Room_for_4p',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.BinaryField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_created_4p', to=settings.AUTH_USER_MODEL)),
                ('fourth_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_joined_4p_4th', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_4p', to='pages.interactivegame')),
                ('second_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_joined_4p', to=settings.AUTH_USER_MODEL)),
                ('third_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_joined_4p_3rd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room_for_3p',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.BinaryField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_created_3p', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_3p', to='pages.interactivegame')),
                ('second_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_joined_3p', to=settings.AUTH_USER_MODEL)),
                ('third_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_joined_3p_3rd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room_for_2p',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.BinaryField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_created_2p', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_2p', to='pages.interactivegame')),
                ('second_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_joined_2p', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
