# Generated by Django 4.2.11 on 2024-05-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0045_alter_room_for_3p_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_for_2p',
            name='key',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='room_for_4p',
            name='key',
            field=models.TextField(null=True),
        ),
    ]
