# Generated by Django 4.2.11 on 2024-05-31 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0046_alter_room_for_2p_key_alter_room_for_4p_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_for_2p',
            name='gameRef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms_reference_2p', to='pages.interactive'),
        ),
        migrations.AddField(
            model_name='room_for_3p',
            name='gameRef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms_reference_4p', to='pages.interactive'),
        ),
        migrations.AddField(
            model_name='room_for_4p',
            name='gameRef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms_reference_3p', to='pages.interactive'),
        ),
    ]
