# Generated by Django 4.2.11 on 2024-06-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_room_for_2p_gameref_room_for_3p_gameref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='fourth_player_respond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respond', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='second_player_respond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respond', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='third_player_respond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respond', models.TextField(null=True)),
            ],
        ),
    ]
