# Generated by Django 4.2.11 on 2024-06-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0048_fourth_player_respond_second_player_respond_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagesetting',
            name='TranslateLanguage',
            field=models.CharField(choices=[('en-US', 'English'), ('es-ES', 'Spanish'), ('de-DE', 'German'), ('fr-FR', 'French'), ('tr-TR', 'Turkish'), ('ar-XA', 'Arabic'), ('it-IT', 'Italian'), ('ru-RU', 'Russian')], default='en-US', max_length=50),
        ),
    ]
