# Generated by Django 4.2.11 on 2024-06-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0049_languagesetting_translatelanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_for_2p',
            name='isOpen',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='room_for_3p',
            name='isOpen',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='room_for_4p',
            name='isOpen',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
