# Generated by Django 4.2.11 on 2024-05-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='key',
            field=models.TextField(null=True),
        ),
    ]
