# Generated by Django 4.2.11 on 2024-05-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messages_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='key',
            field=models.BinaryField(null=True),
        ),
    ]
