# Generated by Django 4.2.11 on 2024-05-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_messages_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='content',
            field=models.BinaryField(null=True),
        ),
    ]
