# Generated by Django 4.2.11 on 2024-05-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_messages_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
